### ISSUE TITLE
com.android.support:appcompat-v7:23.+ 

### ISSUE THREAD

**Issue by rmard** [echonox/cordova-plugin-snackbar#2]
After adding this plugin, when I try to "cordova build android", the build fails, and I get this message:
- What went wrong:
  A problem occurred configuring root project 'android'.
  > Could not resolve all dependencies for configuration ':_debugCompile'.
  > Could not find any version that matches com.android.support:appcompat-v7:23.+.
   Versions that do not match:
       24.1.1
       24.1.0
       24.0.0
   Searched in the following locations:
       https://repo1.maven.org/maven2/com/android/support/appcompat-v7/maven-metadata.xml
       https://repo1.maven.org/maven2/com/android/support/appcompat-v7/
       https://jcenter.bintray.com/com/android/support/appcompat-v7/maven-metadata.xml
   Required by:
       :android:unspecified
  > Could not find any version that matches com.android.support:design:23.+.
   Versions that do not match:
       24.1.1
       24.1.0
       24.0.0
   Searched in the following locations:
       https://repo1.maven.org/maven2/com/android/support/design/maven-metadata.xml
       https://repo1.maven.org/maven2/com/android/support/design/
       https://jcenter.bintray.com/com/android/support/design/maven-metadata.xml
   Required by:
       :android:unspecified

I think it might be related to the new Android API 24, but I couldn't solve the problem.

**Comment by rmard** [comment]
This commit on other plugin seems to resolve a similar issue

 https://github.com/dpa99c/cordova-diagnostic-plugin/commit/adb2d25cb8d06fbf8c7293250d747a4fd3ff51f8

**Comment by angjelkom** [comment]
@rmard What Build Version do you have? as I know cordova needs the Android API 23 so it should not be a problem

**Comment by rmard** [comment]
@echonox 

```
$ cordova -version
6.3.1
```

I've got it working after cleaning up some files on Android folder and building the project again with this modification on _plugins/cordova-plugin-snackbar/plugin.xml_:

```
        <framework src="com.android.support:appcompat-v7:+" />
        <framework src="com.android.support:design:+" />
```

**Comment by angjelkom** [comment]
Fixed in: [Keep using latest framework versions](https://github.com/echonox/cordova-plugin-snackbar/commit/79c6aa331740d38c55b6fdd43fdf308c57ca4bd0)
