### ISSUE TITLE
app crash when i call the plugin

### ISSUE THREAD

**Issue by ishigo1987** [echonox/cordova-plugin-snackbar#3]
hello i update the plugin to 2.1.0 and i have the same issue my app crash when i call the plugin
my code
var textSnackbar = "Downloading";
       var durationSnackbar = "LONG";
       var buttonSnackbar = "cancel";
       callBack = function()
        {
           //downloader.abort(); 
            console.log("abort"); 
        }
       cordova.plugins.snackbar(textSnackbar, durationSnackbar, buttonSnackbar, callBack);
i have the same issue when i copy paste your example code

**Comment by angjelkom** [comment]
@ishigo1987 plz paste me your cordova version

**Comment by angjelkom** [comment]
@ishigo1987 try running this command in terminal and paste the log you get when app crashes:

> adb -d logcat packagename:V

**Comment by ishigo1987** [comment]
i don't know how to running this command in terminal
i'm using intel xdk with cordova cli 6.2.0
and crosswalk 22 beta
perhaps it's the origin of the problem

**Comment by angjelkom** [comment]
@ishigo1987 I installed Intel XDK and looked in the build system and the latest cordova available is Cordova 6.2.0, unfortunately the future that modifies the AndroidManifest file is available in Cordova 6.3.0 and improved (fixed) in Cordova 6.3.1 I am sorry but you have to wait for Intel to update the CLI, closing ticket as there is no issue.
