### ISSUE TITLE
INFINITE LENGTH Snackbar, dismiss programmatically.

### ISSUE THREAD

**Issue by dpaksoni** [echonox/cordova-plugin-snackbar#5]
How can we display a infinite length Snackbar and dismiss programmatically.

**Comment by angjelkom** [comment]
@dpaksoni dismiss it by clicking the button

**Comment by dpaksoni** [comment]
I do not want to dismiss it by clicking on any button, rather I want to have a reference of Snackbar object and then dismiss whenever I want by clicking snackbarObj.dismiss();

**Comment by angjelkom** [comment]
@dpaksoni Updated the plugin to v2.2.0 with the ability to dismiss the snackbar programmatically.. sorry for the delay.. https://github.com/echonox/cordova-plugin-snackbar/commit/1f2e63e8db90d18ea423445c16203bbffdb8935d
