### ISSUE TITLE
Question: Any way to change z-index of Snackbar?

### ISSUE THREAD

**Issue by jsownz** [echonox/cordova-plugin-snackbar#6]
Currently trying to use the Snackbar plugin (love it!) but I'm also using the inAppBrowser. The inAppBrowser seems to overtake everything and the Snackbar is coming up behind it, so I'm unable to see or interact with it.

Calling the Snackbar before the inAppBrowser is called works like a charm, but as soon as inAppBrowser is called, goodbye Snackbar :(

Currently testing on:
Nexus 5X with Android 7.1.1
Android Emulator (Android Studio) Nexus 5X Android 7.1

**Comment by angjelkom** [comment]
@jsownz Thanks for reporting sorry, I've been busy with work will look at it tonight

**Comment by angjelkom** [comment]
@jsownz Sorry for late response, but this is not doable right now as the inAppBrowser is basically an extended view from the Dialog and as per the official Material Design specs for Snackbar, Dialog has higher priority than the Snackbar:

> Snackbars appear above most elements on screen, and they are equal in elevation to the floating action button. However, they are lower in elevation than **dialogs**, bottom sheets, and navigation drawers.

Closing isssue as there is no bug here..

**Comment by jsownz** [comment]
Thanks for looking into it @echonox
